### ISSUE TITLE
[Tracking] Add Styled Components and create basic styles

### ISSUE THREAD

**Issue by j-sm-n** [la-devs/issue-tracking#10]
## To Do

- [x] Add [Styled Components Gatsby.js](https://www.gatsbyjs.org/docs/styled-components/) plugin (https://github.com/la-devs/issue-tracking/issues/19)
- [ ] Style layout container component (https://github.com/la-devs/issue-tracking/issues/20)
- [ ] Style navbar (https://github.com/la-devs/issue-tracking/issues/24)
- [ ] Style buttons (https://github.com/la-devs/issue-tracking/issues/21)
- [ ] Style inputs (https://github.com/la-devs/issue-tracking/issues/23)
- [ ] Style `h1`, `h2`, `h3`, `h4`, `h5` and base text components (https://github.com/la-devs/issue-tracking/issues/22)
- [ ] Style footer (https://github.com/la-devs/issue-tracking/issues/25)

**Comment by j-sm-n** [comment]
Turing this into a tracking ticket so it's not so daunting 😅
